name: 'Deploy frontend'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Baixar cÃ³digo'
        uses: actions/checkout@v4

      - name: 'Configurar Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 'Instalar dependÃªncias'
        run: npm ci

      - name: 'Instalar NX globalmente'
        run: npx nx build frontend_nepa --configuration=production

      - name: 'Verificar arquivos de build'
        run: ls -la ./dist/frontend_nepa/browser/

      - name: 'Limpar diretÃ³rio no servidor'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }} # ðŸ”‘ TROCA AQUI
          script: |
            rm -rf /frontend/*
            mkdir -p /frontend

      - name: 'Copiar arquivos para servidor'
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }} # ðŸ”‘ TROCA AQUI
          port: ${{ secrets.SSH_PORT }}
          source: './dist/frontend_nepa/browser/*'
          target: '/frontend'
          overwrite: true
